language: java
sudo: required
jdk:
- oraclejdk8
- openjdk7
services:
- docker
before_script:
- mvn jetty:run &
- sleep 5
script:
- |-
  if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ ${TRAVIS_JDK_VERSION} = "oraclejdk8" ]]; then
    echo "condition met"
  fi
