language: java
sudo: required
jdk:
- oraclejdk8
- openjdk7
services:
- docker
before_script:
- mvn jetty:run &
- sleep 5
script:
- |-
  result=./ci/run_tests.sh
  echo result
  if [ ${TRAVIS_BRANCH} = "master"]  && [ ${TRAVIS_JDK_VERSION} = "oraclejdk8" ] && [ ${TRAVIS_PULL_REQUEST} = "false" ]; then
    ./ci/create_image.sh ;
  fi

