language: java
sudo: required
jdk:
- oraclejdk8
- openjdk7
services:
- docker
before_script:
- mvn jetty:run &
- sleep 5
jobs:
    include:
    - stage: verify
      if: not tag is present
      script:
      - image=azuresdk-a01-droid:java-$TRAVIS_BUILD_NUMBER
      - docker build -t $image -f Dockerfile .
      - docker images
    - stage: publish
      if: tag is present
      script:
      - image=azuresdk-a01-droid:java-$TRAVIS_BUILD_NUMBER
      - docker build --pull -t $image -f Dockerfile .
      - docker images
      - docker login libtest.azurecr.io -u $AZURESDKDEV_ACR_SP_USERNAME -p $AZURESDK_ACR_SP_PASSWORD
      - docker tag azuresdk-a01-droid:java-$TRAVIS_BUILD_NUMBER libtest.azurecr.io/azuresdk-a01-droid:java-$TRAVIS_TAG
      - docker tag azuresdk-a01-droid:java-$TRAVIS_BUILD_NUMBER libtest.azurecr.io/azuresdk-a01-droid:java-latest
      - docker push libtest.azurecr.io/azuresdk-a01-droid:java-$TRAVIS_TAG
      - docker push libtest.azurecr.io/azuresdk-a01-droid:java-latest



